### PR TITLE
Allow for server to support TLS if desired

### PR DESCRIPTION
**Pull request by rokett**
It would be handy for the server to support TLS if whoever is running it so desires; this change allows that.

It is up to the operator to provide the certifcate and keyfile.

### CODE REVIEW

**Comment by terickson** [comment]
Really same as the guacd pull request.  I think this is good functionality but I think it should be implemented with [environment variables](https://gobyexample.com/environment-variables) and we need to add it to the readme.

**Comment by rokett** [comment]
yep that makes sense.....I'll wait to see your thoughts on the other PR that I just edited, and then take care of changing this one too.

**Comment by rokett** [comment]
I have updated this to use environment variables rather than flags.  Hope this is good for you?

**Comment by terickson** [comment]
Looks good I'm merge this in and make a new release with both of these changes.

**Comment by rokett** [comment]
that's great......thanks :-)

**Review by me355 — COMMENTED** [review]
Khbb

**Comment by me355** [comment]
> Khbb

Said

**Pull request merged**
